#!/usr/bin/env python3
"""Generate naughty_jokes.json from the joke list."""
import json
import os

jokes = [
    {"setup": "I like my coffee like I like my humor...", "punchline": "Strong, hot, and keeping me up all night."},
    {"setup": "She said I never listen...", "punchline": "Or something like that."},
    {"setup": "He said he could go all night...", "punchline": "Turns out he meant gaming."},
    {"setup": "She said she needed space...", "punchline": "So I gave her the whole bed."},
    {"setup": "I told her I was good with my hands...", "punchline": "She said, prove it. Fix the sink first."},
    {"setup": "She said she likes surprises...", "punchline": "I am still trying to figure out if that is a warning."},
    {"setup": "He is not lazy...", "punchline": "He is just on energy-saving mode. Especially after dark."},
    {"setup": "I tried to be subtle...", "punchline": "But subtle left the room early."},
    {"setup": "I do not sweat...", "punchline": "I sparkle under pressure."},
    {"setup": "He is a hands-on learner...", "punchline": "Sometimes too hands-on."},
    {"setup": "I like long walks...", "punchline": "Especially when they lead somewhere interesting."},
    {"setup": "He said he was experienced...", "punchline": "I think he meant experienced at talking."},
    {"setup": "I am great at multitasking...", "punchline": "I can think about doing things and not do them at the same time."},
    {"setup": "I do not rush things...", "punchline": "I let anticipation do the heavy lifting."},
    {"setup": "He has got stamina...", "punchline": "For watching entire seasons in one night."},
    {"setup": "I told her I was flexible...", "punchline": "She said, mentally or physically?"},
    {"setup": "I am not saying I am irresistible...", "punchline": "But cookies disappear when I am around."},
    {"setup": "She said she wanted something spontaneous...", "punchline": "So I scheduled it."},
    {"setup": "I like to keep things interesting...", "punchline": "Mostly by not explaining anything."},
    {"setup": "He is a smooth talker...", "punchline": "Like butter on a hot pan."},
    {"setup": "She said she likes a challenge...", "punchline": "I handed her my schedule."},
    {"setup": "I am not mysterious...", "punchline": "I just forget to text back."},
    {"setup": "She said take initiative...", "punchline": "So I took the last slice."},
    {"setup": "I am all about chemistry...", "punchline": "Especially when it sparks."},
    {"setup": "He has got great timing...", "punchline": "Just not when it matters."},
    {"setup": "I do not play hard to get...", "punchline": "I just nap a lot."},
    {"setup": "She said she wanted depth...", "punchline": "So I started overthinking."},
    {"setup": "I am not complicated...", "punchline": "You just need the right instructions."},
    {"setup": "He said he was well-rounded...", "punchline": "Mostly around the middle."},
    {"setup": "She said she likes confidence...", "punchline": "So I googled how to get some."},
    {"setup": "I am good under pressure...", "punchline": "Unless it is before noon."},
    {"setup": "He has got a great imagination...", "punchline": "Which helps a lot."},
    {"setup": "I do not need practice...", "punchline": "I just like repetition."},
    {"setup": "She said be bold...", "punchline": "So I wore matching socks."},
    {"setup": "He said he is consistent...", "punchline": "Consistently late."},
    {"setup": "She said she wanted excitement...", "punchline": "I suggested a different restaurant."},
    {"setup": "I am not shy...", "punchline": "I just strategically pause."},
    {"setup": "She said she wanted passion...", "punchline": "I turned up the thermostat."},
    {"setup": "He said he is adventurous...", "punchline": "Tried a new pizza topping once."},
    {"setup": "She said she wanted something unforgettable...", "punchline": "So I told a really bad joke."},
    {"setup": "I told her I would change...", "punchline": "She said she had heard that before."},
    {"setup": "He said forever...", "punchline": "Turns out he meant until something better showed up."},
    {"setup": "I like my relationships like my passwords...", "punchline": "Hard to crack and easy to forget."},
    {"setup": "She said I had baggage...", "punchline": "I said it is carry-on trauma."},
    {"setup": "I do not burn bridges...", "punchline": "I install explosives."},
    {"setup": "He said trust me...", "punchline": "Which is usually when you should not."},
    {"setup": "I am emotionally available...", "punchline": "Just not for long."},
    {"setup": "I do not ghost...", "punchline": "I just fade into legend."},
    {"setup": "He said I was unforgettable...", "punchline": "I think he meant unresolved."},
    {"setup": "She said I was intense...", "punchline": "I said, wait until Act Two."},
    {"setup": "I do not hold grudges...", "punchline": "I nurture them."},
    {"setup": "I am not toxic...", "punchline": "I just have strong reactions."},
    {"setup": "She said I overthink...", "punchline": "I said, about what exactly?"},
    {"setup": "He said I was different...", "punchline": "Then treated me the same."},
    {"setup": "She said I had layers...", "punchline": "Like an onion, but with worse outcomes."},
    {"setup": "I am not dramatic...", "punchline": "The situation just escalates around me."},
    {"setup": "He said it is not you...", "punchline": "Statistically unlikely."},
    {"setup": "She said I needed healing...", "punchline": "I scheduled it for later."},
    {"setup": "He said I deserved better...", "punchline": "And then left."},
    {"setup": "She said I was guarded...", "punchline": "I call it security."},
    {"setup": "He said he cared...", "punchline": "In past tense."},
    {"setup": "I am not broken...", "punchline": "I just have features."},
    {"setup": "She said I was complicated...", "punchline": "I said, you have only seen the intro."},
    {"setup": "He said he would stay...", "punchline": "Plot twist."},
    {"setup": "She said I had walls...", "punchline": "I installed gates too."},
    {"setup": "She said I was hard to read...", "punchline": "I said, good."},
    {"setup": "He said just trust me...", "punchline": "Famous last words."},
    {"setup": "She said I changed...", "punchline": "I said, you noticed?"},
    {"setup": "He said I was enough...", "punchline": "Briefly."},
    {"setup": "She said I was cold...", "punchline": "I said, efficient."},
    {"setup": "I do not break hearts...", "punchline": "I expose weak points."},
    {"setup": "I am not indecisive...", "punchline": "I just like keeping my options equally confused."},
    {"setup": "She said I lack direction...", "punchline": "I said I prefer plot twists."},
    {"setup": "I am not late...", "punchline": "I arrive after expectations."},
    {"setup": "I do not exaggerate...", "punchline": "I optimize reality."},
    {"setup": "She said I talk in circles...", "punchline": "I call it narrative cardio."},
    {"setup": "I am not awkward...", "punchline": "I am unpredictably timed."},
    {"setup": "He said I was too much...", "punchline": "I said, define enough."},
    {"setup": "I do not procrastinate...", "punchline": "I reschedule intention."},
    {"setup": "I am not distracted...", "punchline": "I multitask poorly with confidence."},
    {"setup": "I do not overthink...", "punchline": "I pre-experience outcomes."},
    {"setup": "She said I was vague...", "punchline": "I prefer interpretive communication."},
    {"setup": "I am not stubborn...", "punchline": "I just finish arguments internally."},
    {"setup": "He said I needed clarity...", "punchline": "I dimmed the lights."},
    {"setup": "She said I was difficult...", "punchline": "I said, selectively compatible."},
    {"setup": "I am not forgetful...", "punchline": "I archive aggressively."},
    {"setup": "He said I was unpredictable...", "punchline": "I said, statistically interesting."},
    {"setup": "She said I avoid answers...", "punchline": "I curate them."},
    {"setup": "I am not intense...", "punchline": "I am high-resolution."},
    {"setup": "I do not stall...", "punchline": "I buffer."},
    {"setup": "I am not sarcastic...", "punchline": "I am truth-adjacent."},
    {"setup": "She said I overanalyze...", "punchline": "I said, premium processing."},
    {"setup": "He said I was sharp...", "punchline": "I said, handle carefully."},
    {"setup": "She said I was extra...", "punchline": "I said, deluxe edition."},
    {"setup": "I am not blunt...", "punchline": "I am efficiently direct."},
    {"setup": "I am not difficult...", "punchline": "I am advanced mode."},
    {"setup": "I am not random...", "punchline": "I am creatively unpredictable."},
    {"setup": "He said I overthink...", "punchline": "I said, beta testing reality."},
    {"setup": "She said I was sarcastic...", "punchline": "I said, context dependent."},
    {"setup": "I am not odd...", "punchline": "I am limited edition."},
    {"setup": "She said I was too clever...", "punchline": "I said nothing."},
    {"setup": "I am all about technique...", "punchline": "Results may vary."},
    {"setup": "She said I take my time...", "punchline": "I call it attention to detail."},
    {"setup": "He said I was smooth...", "punchline": "I have had practice."},
    {"setup": "She said I had good hands...", "punchline": "I said, they are trained."},
    {"setup": "I like to build momentum...", "punchline": "Slowly at first."},
    {"setup": "He said I was confident...", "punchline": "I said, experience helps."},
    {"setup": "I do not skip steps...", "punchline": "I follow through."},
    {"setup": "He said I was patient...", "punchline": "I said, it pays off."},
    {"setup": "I do not overdo it...", "punchline": "I pace myself."},
    {"setup": "She said I was attentive...", "punchline": "I notice things."},
    {"setup": "I like a challenge...", "punchline": "Especially hands-on."},
    {"setup": "He said I was consistent...", "punchline": "I deliver."},
    {"setup": "I do not cut corners...", "punchline": "I explore them."},
    {"setup": "I like feedback...", "punchline": "Helps improve performance."},
    {"setup": "He said I was thorough...", "punchline": "I said, always."},
    {"setup": "I do not guess...", "punchline": "I learn by doing."},
    {"setup": "She said I had stamina...", "punchline": "I smiled."},
    {"setup": "He said I was skilled...", "punchline": "I did not argue."},
    {"setup": "I do not stop early...", "punchline": "I finish properly."},
    {"setup": "She said I was deliberate...", "punchline": "I said, precision counts."},
    {"setup": "He said I was adaptable...", "punchline": "I adjust quickly."},
    {"setup": "She said I had timing...", "punchline": "I said, it is everything."},
    {"setup": "He said I was confident...", "punchline": "I said, earned."},
    {"setup": "I do not rush results...", "punchline": "I build them."},
    {"setup": "She said I was focused...", "punchline": "I said, locked in."},
    {"setup": "He said I was steady...", "punchline": "I said, reliable."},
    {"setup": "I do not hesitate...", "punchline": "I act."},
    {"setup": "She said I was smooth...", "punchline": "I said, habit."},
    {"setup": "He said I was prepared...", "punchline": "I said, always."},
    {"setup": "She said I was skilled...", "punchline": "I said, refined."},
    {"setup": "He said I was consistent...", "punchline": "I said, on repeat."},
    {"setup": "I do not stop halfway...", "punchline": "I see it through."},
    {"setup": "She said I was confident...", "punchline": "I said, you noticed."},
    {"setup": "He said I was calm...", "punchline": "I said, controlled."},
    {"setup": "I do not miss details...", "punchline": "They matter."},
    {"setup": "She said I was good...", "punchline": "I said, I know."},
]

out = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "naughty_jokes.json")
with open(out, "w") as f:
    json.dump(jokes, f, indent=2)
print(f"Saved {len(jokes)} jokes to {out}")
